---
title: "assignment0"
author: "Xinyu Hu"
date: "2021/2/7"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1.1  Simple object manipulation, vectors and matrices
```{r}
x = 3
x
x==3; x==4
```
```{r}
y = c(x,6)
y
```
```{r}
1:10
seq(0,10,length=40)
```
```{r}
rep(2,5)
rep(1:3,5)
```
```{r}
y=c(1.4,1.6,7.5,3.1,9.5,1.0,3.8,2)
length(y)
```
```{r}
y[2]
y[c(1,4,5)]
y[-1]
y<4
y[y<4]
```
```{r}
y[-5]
```
```{r}
matrix(1:6,nrow=2)
```
```{r}
matrix(1:6,ncol=3)
```
```{r}
M=matrix(1:6,ncol=3,byrow=TRUE)
M
```
```{r}
dim(M);nrow(M);ncol(M)
```
```{r}
M[2,3]; M[,3]; M[2,]; M[1,1:2]; M[1,1:3]; M[1,2:3]
```
```{r}
t(M)
```
```{r}
A=matrix(1:8,ncol=4,byrow=TRUE)
A
B=matrix(1:8,nrow=4,byrow=TRUE)
B
```
```{r}
Bt = t(B)
Bt
```
```{r}
A+Bt
A-Bt
A%*%B
```
```{r}
C=matrix(1:4,ncol=2,byrow=TRUE)
C
det(C)
solve(C)
```

1.2 Plotting
```{r}
help(boxplot); boxplot(y)
```
```{r}
z=c(2.7,4.3,9.5,1.4,5.5,7.2); boxplot(y,z)
```
```{r}
x=seq(0,10,length=30);x
y=sin(x);y
```

```{r}
plot(x,sin(x))
plot(x,sin(x),type="l",xlab="x",ylab="sin(x)")
```
```{r}

```


